"""empty message

Revision ID: 73c1c2f3fe83
Revises: 6fa9a7629442
Create Date: 2022-07-25 13:35:12.440806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73c1c2f3fe83'
down_revision = '6fa9a7629442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app', sa.Column('status', sa.Integer(), nullable=True))
    op.add_column('project', sa.Column('status', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'status')
    op.drop_column('project', 'status')
    op.drop_column('app', 'status')
    # ### end Alembic commands ###
