"""empty message

Revision ID: e4a301ce4a06
Revises: 2a50347e3993
Create Date: 2022-08-05 08:10:22.555977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4a301ce4a06'
down_revision = '2a50347e3993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app', sa.Column('it_status', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'project', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_column('app', 'it_status')
    # ### end Alembic commands ###
